[package]
name = "wuxia_clan_war"
version = "0.1.0"
authors = ["Andrey <dewshick@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
num-iter = "0.1"
ggez = "0.5.0-rc.0"
itertools = "0.8.0"
fps_counter = "1.0.0"
ordered-float = "1.0"
