[package]
name = "wuxia_clan_war"
version = "0.1.0"
authors = ["Andrey <dewshick@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.81.0"
rand = "0.6"
sdl2 = "0.31"
num-iter = "0.1"
ggez = "0.5.0-rc.0"
gl = "0.10.0"
itertools = "0.8.0"
fps_counter = "1.0.0"